version: "3"

networks:
  monitoring:

volumes:
  vol_prometheus:
  vol_grafana_db:
  vol_grafana_conf:

services:
  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION:-v0.26.1}
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock,readonly
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

  node-exporter:
    image: basi/node-exporter:${NODE_EXPORTER_VERSION:-latest}
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - /etc/hostname:/etc/host_hostname
    hostname: "{{.Node.ID}}"
    environment:
      HOST_HOSTNAME: /etc/host_hostname
    command: --path.procfs "/host/proc" --path.sysfs /host/sys --collector.textfile.directory /etc/node-exporter/ --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
        reservations:
          cpus: '0.10'
          memory: 16M


  prometheus:
    image: basi/prometheus-swarm:${PROMETHEUS_SWARM_VERSION:-latest}
    ports:
      - "9090"
    networks:
      - monitoring
    volumes:
      - vol_prometheus:/prometheus
    command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles -alertmanager.url=http://alertmanager:9093
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 128M

  grafana:
    image: basi/grafana:${GRAFANA_VERSION:-4.4.3}
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - vol_grafana_db:/var/lib/grafana
      - vol_grafana_conf:/etc/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD:-P0o9i8u7}
      PROMETHEUS_ENDPOINT: http://prometheus:9090
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 64M
        reservations:
          cpus: '0.50'
          memory: 32M